### PR TITLE
Fix speed dial on sidebar

### LINKED ISSUE #226: New desing - fix speed dial
With a new sidebar, assigning speed dial is broken.

### PR DESCRIPTION
**Pull request by FrantisekMichalSebestyen**
Make speed dial work for Issue input on JIRA Sidebar.
Delete speed dial dialog.

resolves #226

### CODE REVIEW

File: src/consts.js [hunk 1]
```diff
@@ -1,12 +1,10 @@
 // @flow
 export type Mode = 0 | 1
 
-export type Focus = 'description' | 'time' | 'issue'
+export type FocusType = 'description' | 'time' | 'issue'
+export type Focus = { type: FocusType, payload?: any }
```
Comment (domiin50) [inline src/consts.js]: Move this to _state.js_ It is used only there and it is not needed to be exported.

File: src/tracker/JiraSidebar/IssueInput.js [hunk 2]
```diff
@@ -45,23 +46,27 @@ const IssueInput = ({
...
-      onChange={handleChange}
-      defaultOptions={recentIssues}
-      loadOptions={loadOptions}
-      theme={mutateTheme}
-      ref={handleRef}
-    />
-  </div>
-)
+}: Props) => {
+  return (
```
Comment (domiin50) [inline src/tracker/JiraSidebar/IssueInput.js]: `=> { return(<Component />) }`
Could be written as:
`=> (<Component />)`
No need to use return.

File: src/tracker/JiraSidebar/IssueInput.js [hunk 3]
```diff
@@ -73,14 +78,30 @@ export default compose(
...
-      saveRecentIssue: _saveRecentIssue
+      saveRecentIssue: _saveRecentIssue,
+      setSpeedDialOption: _setSpeedDialOption
     }
   ),
   withState('option', 'setOption', null),
+  withFocusListener(FOCUSES.ISSUE),
+  withHandlers({
+    handleBlur: ({ setPayload }) => () => setPayload(null)
+  }),
```
Comment (domiin50) [inline src/tracker/JiraSidebar/IssueInput.js]: No need to wrap it into another `withHandlers` HOC. Move `handleBlur` to `withHandlers` HOC below.

File: src/tracker/JiraSidebar/IssueInput.js [hunk 4]
```diff
@@ -73,14 +78,30 @@ export default compose(
...
+      setJiraIssue,
+      saveRecentIssue,
+      setSpeedDialOption
+    }) => () => {
+      const optionValue = option ? option.value : null
+      payload
+        ? setSpeedDialOption(payload, optionValue)
+        : setJiraIssue(optionValue)
+
+      option && saveRecentIssue(optionValue)
```
Comment (domiin50) [inline src/tracker/JiraSidebar/IssueInput.js]: I like it :heart_eyes: :+1:
